/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAgendaIndexRouteImport } from './routes/_authenticated/agenda/index'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes/index'
import { Route as AuthenticatedCompromissosIndexRouteImport } from './routes/_authenticated/compromissos/index'
import { Route as AuthenticatedConfiguracoesIndexRouteImport } from './routes/_authenticated/configuracoes/index'
import { Route as AuthenticatedContatosIndexRouteImport } from './routes/_authenticated/contatos/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedEmpresarialIndexRouteImport } from './routes/_authenticated/empresarial/index'
import { Route as AuthenticatedNotificacoesIndexRouteImport } from './routes/_authenticated/notificacoes/index'
import { Route as AuthenticatedPessoalIndexRouteImport } from './routes/_authenticated/pessoal/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaIndexRoute =
  AuthenticatedAgendaIndexRouteImport.update({
    id: '/agenda/',
    path: '/agenda/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompromissosIndexRoute =
  AuthenticatedCompromissosIndexRouteImport.update({
    id: '/compromissos/',
    path: '/compromissos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesIndexRoute =
  AuthenticatedConfiguracoesIndexRouteImport.update({
    id: '/configuracoes/',
    path: '/configuracoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContatosIndexRoute =
  AuthenticatedContatosIndexRouteImport.update({
    id: '/contatos/',
    path: '/contatos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresarialIndexRoute =
  AuthenticatedEmpresarialIndexRouteImport.update({
    id: '/empresarial/',
    path: '/empresarial/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificacoesIndexRoute =
  AuthenticatedNotificacoesIndexRouteImport.update({
    id: '/notificacoes/',
    path: '/notificacoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPessoalIndexRoute =
  AuthenticatedPessoalIndexRouteImport.update({
    id: '/pessoal/',
    path: '/pessoal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda/': typeof AuthenticatedAgendaIndexRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/compromissos/': typeof AuthenticatedCompromissosIndexRoute
  '/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/contatos/': typeof AuthenticatedContatosIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/empresarial/': typeof AuthenticatedEmpresarialIndexRoute
  '/notificacoes/': typeof AuthenticatedNotificacoesIndexRoute
  '/pessoal/': typeof AuthenticatedPessoalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaIndexRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/compromissos': typeof AuthenticatedCompromissosIndexRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesIndexRoute
  '/contatos': typeof AuthenticatedContatosIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/empresarial': typeof AuthenticatedEmpresarialIndexRoute
  '/notificacoes': typeof AuthenticatedNotificacoesIndexRoute
  '/pessoal': typeof AuthenticatedPessoalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda/': typeof AuthenticatedAgendaIndexRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/compromissos/': typeof AuthenticatedCompromissosIndexRoute
  '/_authenticated/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/_authenticated/contatos/': typeof AuthenticatedContatosIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/empresarial/': typeof AuthenticatedEmpresarialIndexRoute
  '/_authenticated/notificacoes/': typeof AuthenticatedNotificacoesIndexRoute
  '/_authenticated/pessoal/': typeof AuthenticatedPessoalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda/'
    | '/clientes/'
    | '/compromissos/'
    | '/configuracoes/'
    | '/contatos/'
    | '/dashboard/'
    | '/empresarial/'
    | '/notificacoes/'
    | '/pessoal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/clientes'
    | '/compromissos'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/empresarial'
    | '/notificacoes'
    | '/pessoal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda/'
    | '/_authenticated/clientes/'
    | '/_authenticated/compromissos/'
    | '/_authenticated/configuracoes/'
    | '/_authenticated/contatos/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/empresarial/'
    | '/_authenticated/notificacoes/'
    | '/_authenticated/pessoal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda/': {
      id: '/_authenticated/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AuthenticatedAgendaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compromissos/': {
      id: '/_authenticated/compromissos/'
      path: '/compromissos'
      fullPath: '/compromissos/'
      preLoaderRoute: typeof AuthenticatedCompromissosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/': {
      id: '/_authenticated/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contatos/': {
      id: '/_authenticated/contatos/'
      path: '/contatos'
      fullPath: '/contatos/'
      preLoaderRoute: typeof AuthenticatedContatosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresarial/': {
      id: '/_authenticated/empresarial/'
      path: '/empresarial'
      fullPath: '/empresarial/'
      preLoaderRoute: typeof AuthenticatedEmpresarialIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes/': {
      id: '/_authenticated/notificacoes/'
      path: '/notificacoes'
      fullPath: '/notificacoes/'
      preLoaderRoute: typeof AuthenticatedNotificacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pessoal/': {
      id: '/_authenticated/pessoal/'
      path: '/pessoal'
      fullPath: '/pessoal/'
      preLoaderRoute: typeof AuthenticatedPessoalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaIndexRoute: typeof AuthenticatedAgendaIndexRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedCompromissosIndexRoute: typeof AuthenticatedCompromissosIndexRoute
  AuthenticatedConfiguracoesIndexRoute: typeof AuthenticatedConfiguracoesIndexRoute
  AuthenticatedContatosIndexRoute: typeof AuthenticatedContatosIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedEmpresarialIndexRoute: typeof AuthenticatedEmpresarialIndexRoute
  AuthenticatedNotificacoesIndexRoute: typeof AuthenticatedNotificacoesIndexRoute
  AuthenticatedPessoalIndexRoute: typeof AuthenticatedPessoalIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaIndexRoute: AuthenticatedAgendaIndexRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedCompromissosIndexRoute: AuthenticatedCompromissosIndexRoute,
  AuthenticatedConfiguracoesIndexRoute: AuthenticatedConfiguracoesIndexRoute,
  AuthenticatedContatosIndexRoute: AuthenticatedContatosIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedEmpresarialIndexRoute: AuthenticatedEmpresarialIndexRoute,
  AuthenticatedNotificacoesIndexRoute: AuthenticatedNotificacoesIndexRoute,
  AuthenticatedPessoalIndexRoute: AuthenticatedPessoalIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
